# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/probation training/linux laptop ip_repo/ip_repo/Azimuth_test_axi_1.0/src/mult_gen_1/mult_gen_1.xci
# IP: The module: 'mult_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/probation training/linux laptop ip_repo/ip_repo/Azimuth_test_axi_1.0/src/mult_gen_1/mult_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Projects/probation training/linux laptop ip_repo/ip_repo/Azimuth_test_axi_1.0/src/mult_gen_1/mult_gen_1.xci
# IP: The module: 'mult_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/probation training/linux laptop ip_repo/ip_repo/Azimuth_test_axi_1.0/src/mult_gen_1/mult_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
